### ISSUE TITLE
Create Custom Objects with Fields

### ISSUE THREAD

**Issue by AkashBangalkar** [Isha-Flex/Salesforce-Work#1]
- [x] Create Custom Object - **Vehicle**
- [x] Default Field - Text - Vehicle Name
- [x] Registration Number (Text - 10)
- [x] Company (Picklist) [Toyota, Audi, BMW, Ford, Porsche, Tata, Maruti, Other]
- [x] Registration Year (Text - 4)
- [x] Seating Capacity (Picklist) [3, 4, 5, 6, 7]
- [x] Passing State (Text - 2)
- [x] Body Colour (Text - 10)
- [x] Owner Name (Text - 50)
- [x] Current Status (Picklist) [Active, Damaged, Renewed, Expired]
- [x] VL on "Registration Year" - Year should be number only and it should not be greater than current year
- [x] VL on "Passing State" - Passing State should accept only capital letters
- [x] Create Lightning Record Page
- [x] Create Path for "Current Status"

**Comment by Isha-Flex** [comment]
Task Completed - Please Review

**Comment by AkashBangalkar** [comment]
- Vehcile Spelling Wrong
- Picklist Field Value Spelling - ']'

**Comment by AkashBangalkar** [comment]
Reviewed - Ready to Close!!
